/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrailleRouteImport } from './routes/braille'
import { Route as HapticsRouteImport } from './routes/haptics'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IslRouteImport } from './routes/isl'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VoiceRouteImport } from './routes/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrailleRoute = BrailleRouteImport.update({
  id: '/braille',
  path: '/braille',
  getParentRoute: () => rootRouteImport,
} as any)
const HapticsRoute = HapticsRouteImport.update({
  id: '/haptics',
  path: '/haptics',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IslRoute = IslRouteImport.update({
  id: '/isl',
  path: '/isl',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/braille': typeof BrailleRoute
  '/haptics': typeof HapticsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/isl': typeof IslRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/braille': typeof BrailleRoute
  '/haptics': typeof HapticsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/isl': typeof IslRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/braille': typeof BrailleRoute
  '/haptics': typeof HapticsRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/isl': typeof IslRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/braille'
    | '/haptics'
    | '/history'
    | '/home'
    | '/isl'
    | '/onboarding'
    | '/settings'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/braille'
    | '/haptics'
    | '/history'
    | '/home'
    | '/isl'
    | '/onboarding'
    | '/settings'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/braille'
    | '/haptics'
    | '/history'
    | '/home'
    | '/isl'
    | '/onboarding'
    | '/settings'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrailleRoute: typeof BrailleRoute
  HapticsRoute: typeof HapticsRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  IslRoute: typeof IslRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/braille': {
      id: '/braille'
      path: '/braille'
      fullPath: '/braille'
      preLoaderRoute: typeof BrailleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haptics': {
      id: '/haptics'
      path: '/haptics'
      fullPath: '/haptics'
      preLoaderRoute: typeof HapticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isl': {
      id: '/isl'
      path: '/isl'
      fullPath: '/isl'
      preLoaderRoute: typeof IslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrailleRoute: BrailleRoute,
  HapticsRoute: HapticsRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  IslRoute: IslRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
